INSERT INTO TRAINEE VALUES (1, 'Daniel', 'Osagie', 'June')
INSERT INTO TRAINEE VALUES (2, 'naomi', 'Stanley', 'June')
INSERT INTO TRAINEE VALUES (3, 'Syed', 'Ahmed', 'June')
INSERT INTO TRAINEE VALUES (4, 'Adam', 'Afzal', 'June')
INSERT INTO TRAINEE VALUES (5, 'Shiyamalan', 'Sunthar', 'June')
INSERT INTO SUBJECT (id, subjectname, rating, trainee_id) VALUES (1, 'Java EE', '8', '3')
INSERT INTO SUBJECT (id, subjectname, rating, trainee_id) VALUES (2, 'MySQL', '4', '2')
INSERT INTO SUBJECT (id, subjectname, rating, trainee_id) VALUES (3, 'AngularJS', '10000000', '1')
INSERT INTO SUBJECT (id, subjectname, rating, trainee_id) VALUES (4, 'HTML/PHP', '2', '4')
INSERT INTO SUBJECT (id, subjectname, rating, trainee_id) VALUES (5, 'Agile', '6', '5')
